# Localization.ps1 - Multi-language support (FR, EN, ES, IT)

$Script:CurrentLanguage = "FR"

$Script:Strings = @{
    # ============================================================
    # FRANCAIS
    # ============================================================
    "FR" = @{
        # --- App ---
        AppTitle          = "TIA Openness Tool"
        AppSubtitle       = "Export DataBlocks TIA Portal"

        # --- Navigation ---
        NavConnection     = "Connexion"
        NavExport         = "Export DataBlocks"

        # --- Version ---
        LblVersion        = "Version TIA Portal :"
        LblNoVersion      = "Aucune version TIA Portal detectee."
        LblDllLoaded      = "DLL chargee : {0}"
        LblDllError       = "Erreur de chargement DLL"
        LblVersionLocked  = "Version verrouillee (connecte)"

        # --- Connection Page ---
        PageConnection    = "Connexion TIA Portal"
        BtnScan           = "Scanner les instances TIA Portal"
        LblInstances      = "Instances disponibles"
        BtnConnect        = "Se connecter"
        BtnDisconnect     = "Se deconnecter"
        LblConnected      = "Connecte"
        LblDisconnected   = "Deconnecte"
        LblScanResult     = "{0} instance(s) trouvee(s)"
        LblNoInstance     = "Aucune instance TIA Portal trouvee"
        LblProject        = "Projet : {0}"
        LblPlcCount       = "{0} automate(s) detecte(s)"

        # --- Export Page ---
        PageExport        = "Export DataBlocks"
        BtnLoadDBs        = "Charger les DataBlocks"
        BtnSelectAll      = "Tout selectionner"
        BtnDeselectAll    = "Tout deselectionner"
        LblHideInstanceDB = "Masquer les DBs d'instance"
        LblDBCount        = "{0} DB(s)"
        LblExportFolder   = "Dossier :"
        LblDefaultFolder  = "Bureau (par defaut)"
        BtnExportCsv      = "Exporter Table CSV"
        TypeGlobal        = "Global"
        TypeInstance      = "Instance"
        LblPlc            = "PLC {0}"

        # --- PLC Info ---
        LblPlcName        = "PLC : {0}"
        LblPlcIp          = "IP : {0}"
        LblPlcTsap        = "TSAP : {0}"
        BtnEditPlcInfo    = "Editer"
        DlgPlcInfoTitle   = "Informations PLC"
        DlgPlcName        = "Nom du PLC :"
        DlgPlcIp          = "Adresse IP :"
        DlgPlcTsap        = "TSAP :"

        # --- CSV Export ---
        RowPlcName        = "Nom automate"
        RowIpAddress      = "Adresse IP"
        RowTsap           = "TSAP"
        ColTag            = "TAG"
        ColDB             = "DB"
        ColOffset         = "Decalage"
        ColType           = "Type"
        ColDescription    = "Description"
        ColUnit           = "Unite"
        ColRepere         = "Repere"
        ColCoef           = "Coef"
        MsgExportCsvDone  = "Export CSV termine !"
        MsgOptimizedWarning = "DB optimises (sans offset) :"
        MsgXmlExportError = "{0} : Erreur export XML"
        MsgXmlParseError  = "{0} : Erreur parsing XML"

        # --- Messages ---
        MsgError          = "Erreur"
        MsgInfo           = "Information"
        MsgConfirm        = "Confirmation"
        MsgNoInstance     = "Veuillez selectionner une instance TIA Portal."
        MsgConnectFirst   = "Veuillez d'abord vous connecter a TIA Portal."
        MsgNoSelection    = "Veuillez selectionner au moins un DataBlock."
        MsgScanError      = "Erreur lors du scan :`n{0}"
        MsgConnectError   = "Erreur de connexion :`n{0}"
        MsgOpennessSecurityError = "Acces TIA Openness refuse (erreur de securite).`n`nLe compte Windows qui execute TIA Portal n'est pas membre du groupe local << Siemens TIA Openness >>.`n`nSolution (en administrateur) : ajoutez l'utilisateur a ce groupe via lusrmgr.msc, ou en ligne de commande :`n  net localgroup `"Siemens TIA Openness`" `"{0}`" /add`n`nFermez ensuite la session Windows (ou redemarrez) puis relancez TIA Portal.`n`nDetail :`n{1}"
        BtnCopyCommand    = "Copier la commande"
        MsgCopied         = "Commande copiee dans le presse-papier."
        MsgConnectOk      = "Connecte au projet : {0}`n{1} automate(s) detecte(s)"
        MsgDisconnectOk   = "Deconnecte."
        MsgLoadError      = "Erreur lors du chargement :`n{0}"
        MsgExportSuccess  = "Reussis : {0}"
        MsgExportErrors   = "Erreurs : {0}"
        MsgExportFolder   = "Dossier : {0}"
        MsgExportDetail   = "Details des erreurs :"
        MsgConfirmClose   = "Un export est en cours. Voulez-vous vraiment fermer ?"
        MsgNoProject      = "Aucun projet ouvert dans TIA Portal."
        MsgNoPlc          = "Aucun automate (PLC) trouve dans le projet."
        MsgProcessNotFound = "Processus TIA Portal introuvable."
        MsgBlockNotFound  = "{0} : Bloc introuvable"
        MsgDllRequired    = "Veuillez d'abord selectionner une version TIA Portal."
        MsgRestartRequired = "La DLL est deja chargee. Un changement de version necessite de redemarrer l'application."

        # --- Tooltips ---
        TipScan           = "Rechercher les instances TIA Portal en cours d'execution"
        TipConnect        = "Se connecter a l'instance selectionnee"
        TipDisconnect     = "Se deconnecter de TIA Portal"
        TipLoadDBs        = "Charger la liste des DataBlocks du projet"
        TipExportCsv      = "Exporter les DataBlocks selectionnes en table CSV (1 fichier par PLC)"
        TipBrowse         = "Choisir le dossier d'export"

        # --- Export Format ---
        LblExportFormat   = "Format d'export :"
        OptCsvSiemens     = "Table d'echange CSV"
        OptVarLstEwon     = "var_lst (Ewon)"
        OptPcVue          = "PcVue Architect (.csv)"
        LblEwonRepere     = "Prefixe tag (opt.) :"
        LblEwonTopic      = "Topic :"
        LblEwonPage       = "Page :"
        BtnExportEwon     = "Exporter var_lst"
        TipExportEwon     = "Exporter les DataBlocks selectionnes en var_lst.csv (Ewon Flexy)"
        MsgExportEwonDone = "Export var_lst termine !"
        BtnExportPcVue    = "Exporter PcVue"
        TipExportPcVue    = "Exporter au format PcVue Architect (1 fichier CSV par DB)"
        MsgExportPcVueDone = "Export PcVue termine !"
        MsgInconsistentBlock = "Bloc inconsistant --compilez le projet TIA Portal avant l'export"
        MsgOnlineModeError = "Export impossible en mode connecte (en ligne sur l'automate). Passez TIA Portal hors ligne (deconnexion de l'automate) puis relancez l'export."
        MsgOnlinePlcList  = "Automate(s) concerne(s) : {0}"

        # --- Language ---
        LangLabel         = "Langue :"
    }

    # ============================================================
    # ENGLISH
    # ============================================================
    "EN" = @{
        # --- App ---
        AppTitle          = "TIA Openness Tool"
        AppSubtitle       = "TIA Portal DataBlock Export"

        # --- Navigation ---
        NavConnection     = "Connection"
        NavExport         = "Export DataBlocks"

        # --- Version ---
        LblVersion        = "TIA Portal Version:"
        LblNoVersion      = "No TIA Portal version detected."
        LblDllLoaded      = "DLL loaded: {0}"
        LblDllError       = "DLL loading error"
        LblVersionLocked  = "Version locked (connected)"

        # --- Connection Page ---
        PageConnection    = "TIA Portal Connection"
        BtnScan           = "Scan TIA Portal instances"
        LblInstances      = "Available instances"
        BtnConnect        = "Connect"
        BtnDisconnect     = "Disconnect"
        LblConnected      = "Connected"
        LblDisconnected   = "Disconnected"
        LblScanResult     = "{0} instance(s) found"
        LblNoInstance     = "No TIA Portal instance found"
        LblProject        = "Project: {0}"
        LblPlcCount       = "{0} PLC(s) detected"

        # --- Export Page ---
        PageExport        = "Export DataBlocks"
        BtnLoadDBs        = "Load DataBlocks"
        BtnSelectAll      = "Select all"
        BtnDeselectAll    = "Deselect all"
        LblHideInstanceDB = "Hide instance DBs"
        LblDBCount        = "{0} DB(s)"
        LblExportFolder   = "Folder:"
        LblDefaultFolder  = "Desktop (default)"
        BtnExportCsv      = "Export CSV Table"
        TypeGlobal        = "Global"
        TypeInstance      = "Instance"
        LblPlc            = "PLC {0}"

        # --- PLC Info ---
        LblPlcName        = "PLC: {0}"
        LblPlcIp          = "IP: {0}"
        LblPlcTsap        = "TSAP: {0}"
        BtnEditPlcInfo    = "Edit"
        DlgPlcInfoTitle   = "PLC Information"
        DlgPlcName        = "PLC Name:"
        DlgPlcIp          = "IP Address:"
        DlgPlcTsap        = "TSAP:"

        # --- CSV Export ---
        RowPlcName        = "PLC Name"
        RowIpAddress      = "IP Address"
        RowTsap           = "TSAP"
        ColTag            = "TAG"
        ColDB             = "DB"
        ColOffset         = "Offset"
        ColType           = "Type"
        ColDescription    = "Description"
        ColUnit           = "Unit"
        ColRepere         = "Reference"
        ColCoef           = "Coef"
        MsgExportCsvDone  = "CSV export completed!"
        MsgOptimizedWarning = "Optimized DBs (no offset):"
        MsgXmlExportError = "{0}: XML export error"
        MsgXmlParseError  = "{0}: XML parsing error"

        # --- Messages ---
        MsgError          = "Error"
        MsgInfo           = "Information"
        MsgConfirm        = "Confirmation"
        MsgNoInstance     = "Please select a TIA Portal instance."
        MsgConnectFirst   = "Please connect to TIA Portal first."
        MsgNoSelection    = "Please select at least one DataBlock."
        MsgScanError      = "Error during scan:`n{0}"
        MsgConnectError   = "Connection error:`n{0}"
        MsgOpennessSecurityError = "TIA Openness access denied (security error).`n`nThe Windows account running TIA Portal is not a member of the local group << Siemens TIA Openness >>.`n`nFix (as administrator): add the user to that group via lusrmgr.msc, or from the command line:`n  net localgroup `"Siemens TIA Openness`" `"{0}`" /add`n`nThen sign out of Windows (or reboot) and restart TIA Portal.`n`nDetails:`n{1}"
        BtnCopyCommand    = "Copy command"
        MsgCopied         = "Command copied to clipboard."
        MsgConnectOk      = "Connected to project: {0}`n{1} PLC(s) detected"
        MsgDisconnectOk   = "Disconnected."
        MsgLoadError      = "Error while loading:`n{0}"
        MsgExportSuccess  = "Successful: {0}"
        MsgExportErrors   = "Errors: {0}"
        MsgExportFolder   = "Folder: {0}"
        MsgExportDetail   = "Error details:"
        MsgConfirmClose   = "An export is in progress. Do you really want to close?"
        MsgNoProject      = "No project open in TIA Portal."
        MsgNoPlc          = "No PLC found in the project."
        MsgProcessNotFound = "TIA Portal process not found."
        MsgBlockNotFound  = "{0}: Block not found"
        MsgDllRequired    = "Please select a TIA Portal version first."
        MsgRestartRequired = "DLL already loaded. Changing version requires restarting the application."

        # --- Tooltips ---
        TipScan           = "Search for running TIA Portal instances"
        TipConnect        = "Connect to the selected instance"
        TipDisconnect     = "Disconnect from TIA Portal"
        TipLoadDBs        = "Load the project's DataBlock list"
        TipExportCsv      = "Export selected DataBlocks as CSV table (1 file per PLC)"
        TipBrowse         = "Choose the export folder"

        # --- Export Format ---
        LblExportFormat   = "Export format:"
        OptCsvSiemens     = "CSV Exchange Table"
        OptVarLstEwon     = "var_lst (Ewon)"
        OptPcVue          = "PcVue Architect (.csv)"
        LblEwonRepere     = "Tag prefix (opt.):"
        LblEwonTopic      = "Topic:"
        LblEwonPage       = "Page:"
        BtnExportEwon     = "Export var_lst"
        TipExportEwon     = "Export selected DataBlocks as var_lst.csv (Ewon Flexy)"
        MsgExportEwonDone = "var_lst export completed!"
        BtnExportPcVue    = "Export PcVue"
        TipExportPcVue    = "Export as PcVue Architect format (1 CSV file per DB)"
        MsgExportPcVueDone = "PcVue export completed!"
        MsgInconsistentBlock = "Inconsistent block --compile the TIA Portal project before exporting"
        MsgOnlineModeError = "Export is not possible in online mode (connected to the PLC). Switch TIA Portal offline (disconnect from the PLC) then export again."
        MsgOnlinePlcList  = "Affected PLC(s): {0}"

        # --- Language ---
        LangLabel         = "Language:"
    }

    # ============================================================
    # ESPANOL
    # ============================================================
    "ES" = @{
        AppTitle          = "TIA Openness Tool"
        AppSubtitle       = "Exportar DataBlocks TIA Portal"
        NavConnection     = "Conexion"
        NavExport         = "Exportar DataBlocks"
        LblVersion        = "Version TIA Portal:"
        LblNoVersion      = "No se detecto ninguna version de TIA Portal."
        LblDllLoaded      = "DLL cargada: {0}"
        LblDllError       = "Error al cargar DLL"
        LblVersionLocked  = "Version bloqueada (conectado)"
        PageConnection    = "Conexion TIA Portal"
        BtnScan           = "Buscar instancias TIA Portal"
        LblInstances      = "Instancias disponibles"
        BtnConnect        = "Conectar"
        BtnDisconnect     = "Desconectar"
        LblConnected      = "Conectado"
        LblDisconnected   = "Desconectado"
        LblScanResult     = "{0} instancia(s) encontrada(s)"
        LblNoInstance     = "No se encontro ninguna instancia de TIA Portal"
        LblProject        = "Proyecto: {0}"
        LblPlcCount       = "{0} PLC(s) detectado(s)"
        PageExport        = "Exportar DataBlocks"
        BtnLoadDBs        = "Cargar DataBlocks"
        BtnSelectAll      = "Seleccionar todo"
        BtnDeselectAll    = "Deseleccionar todo"
        LblHideInstanceDB = "Ocultar DBs de instancia"
        LblDBCount        = "{0} DB(s)"
        LblExportFolder   = "Carpeta:"
        LblDefaultFolder  = "Escritorio (por defecto)"
        BtnExportCsv      = "Exportar Tabla CSV"
        TypeGlobal        = "Global"
        TypeInstance      = "Instancia"
        LblPlc            = "PLC {0}"
        LblPlcName        = "PLC: {0}"
        LblPlcIp          = "IP: {0}"
        LblPlcTsap        = "TSAP: {0}"
        BtnEditPlcInfo    = "Editar"
        DlgPlcInfoTitle   = "Informacion del PLC"
        DlgPlcName        = "Nombre del PLC:"
        DlgPlcIp          = "Direccion IP:"
        DlgPlcTsap        = "TSAP:"
        RowPlcName        = "Nombre PLC"
        RowIpAddress      = "Direccion IP"
        RowTsap           = "TSAP"
        ColTag            = "TAG"
        ColDB             = "DB"
        ColOffset         = "Desplazamiento"
        ColType           = "Tipo"
        ColDescription    = "Descripcion"
        ColUnit           = "Unidad"
        ColRepere         = "Referencia"
        ColCoef           = "Coef"
        MsgExportCsvDone  = "Exportacion CSV completada!"
        MsgOptimizedWarning = "DBs optimizados (sin offset):"
        MsgXmlExportError = "{0}: Error exportacion XML"
        MsgXmlParseError  = "{0}: Error parsing XML"
        MsgError          = "Error"
        MsgInfo           = "Informacion"
        MsgConfirm        = "Confirmacion"
        MsgNoInstance     = "Por favor seleccione una instancia de TIA Portal."
        MsgConnectFirst   = "Por favor conectese primero a TIA Portal."
        MsgNoSelection    = "Por favor seleccione al menos un DataBlock."
        MsgScanError      = "Error durante la busqueda:`n{0}"
        MsgConnectError   = "Error de conexion:`n{0}"
        MsgOpennessSecurityError = "Acceso TIA Openness denegado (error de seguridad).`n`nLa cuenta de Windows que ejecuta TIA Portal no es miembro del grupo local << Siemens TIA Openness >>.`n`nSolucion (como administrador): anada el usuario a ese grupo mediante lusrmgr.msc, o por linea de comandos:`n  net localgroup `"Siemens TIA Openness`" `"{0}`" /add`n`nLuego cierre la sesion de Windows (o reinicie) y vuelva a iniciar TIA Portal.`n`nDetalle:`n{1}"
        BtnCopyCommand    = "Copiar el comando"
        MsgCopied         = "Comando copiado al portapapeles."
        MsgConnectOk      = "Conectado al proyecto: {0}`n{1} PLC(s) detectado(s)"
        MsgDisconnectOk   = "Desconectado."
        MsgLoadError      = "Error al cargar:`n{0}"
        MsgExportSuccess  = "Exitosos: {0}"
        MsgExportErrors   = "Errores: {0}"
        MsgExportFolder   = "Carpeta: {0}"
        MsgExportDetail   = "Detalles de errores:"
        MsgConfirmClose   = "Una exportacion esta en curso. Desea cerrar?"
        MsgNoProject      = "No hay proyecto abierto en TIA Portal."
        MsgNoPlc          = "No se encontro ningun PLC en el proyecto."
        MsgProcessNotFound = "Proceso TIA Portal no encontrado."
        MsgBlockNotFound  = "{0}: Bloque no encontrado"
        MsgDllRequired    = "Por favor seleccione una version de TIA Portal primero."
        MsgRestartRequired = "DLL ya cargada. Cambiar de version requiere reiniciar la aplicacion."
        TipScan           = "Buscar instancias de TIA Portal en ejecucion"
        TipConnect        = "Conectar a la instancia seleccionada"
        TipDisconnect     = "Desconectar de TIA Portal"
        TipLoadDBs        = "Cargar la lista de DataBlocks del proyecto"
        TipExportCsv      = "Exportar DataBlocks seleccionados como tabla CSV (1 archivo por PLC)"
        TipBrowse         = "Elegir la carpeta de exportacion"
        # --- Export Format ---
        LblExportFormat   = "Formato de exportacion:"
        OptCsvSiemens     = "Tabla de intercambio CSV"
        OptVarLstEwon     = "var_lst (Ewon)"
        OptPcVue          = "PcVue Architect (.csv)"
        LblEwonRepere     = "Prefijo tag (opc.):"
        LblEwonTopic      = "Topic:"
        LblEwonPage       = "Pagina:"
        BtnExportEwon     = "Exportar var_lst"
        TipExportEwon     = "Exportar DataBlocks seleccionados como var_lst.csv (Ewon Flexy)"
        MsgExportEwonDone = "Exportacion var_lst completada!"
        BtnExportPcVue    = "Exportar PcVue"
        TipExportPcVue    = "Exportar en formato PcVue Architect (1 archivo CSV por DB)"
        MsgExportPcVueDone = "Exportacion PcVue completada!"
        MsgInconsistentBlock = "Bloque inconsistente --compile el proyecto TIA Portal antes de exportar"
        MsgOnlineModeError = "La exportacion no es posible en modo en linea (conectado al PLC). Ponga TIA Portal fuera de linea (desconecte del PLC) y vuelva a exportar."
        MsgOnlinePlcList  = "PLC(s) afectado(s): {0}"
        LangLabel         = "Idioma:"
    }

    # ============================================================
    # ITALIANO
    # ============================================================
    "IT" = @{
        AppTitle          = "TIA Openness Tool"
        AppSubtitle       = "Esportazione DataBlocks TIA Portal"
        NavConnection     = "Connessione"
        NavExport         = "Esporta DataBlocks"
        LblVersion        = "Versione TIA Portal:"
        LblNoVersion      = "Nessuna versione di TIA Portal rilevata."
        LblDllLoaded      = "DLL caricata: {0}"
        LblDllError       = "Errore caricamento DLL"
        LblVersionLocked  = "Versione bloccata (connesso)"
        PageConnection    = "Connessione TIA Portal"
        BtnScan           = "Scansiona istanze TIA Portal"
        LblInstances      = "Istanze disponibili"
        BtnConnect        = "Connetti"
        BtnDisconnect     = "Disconnetti"
        LblConnected      = "Connesso"
        LblDisconnected   = "Disconnesso"
        LblScanResult     = "{0} istanza(e) trovata(e)"
        LblNoInstance     = "Nessuna istanza TIA Portal trovata"
        LblProject        = "Progetto: {0}"
        LblPlcCount       = "{0} PLC rilevati"
        PageExport        = "Esporta DataBlocks"
        BtnLoadDBs        = "Carica DataBlocks"
        BtnSelectAll      = "Seleziona tutto"
        BtnDeselectAll    = "Deseleziona tutto"
        LblHideInstanceDB = "Nascondi DB di istanza"
        LblDBCount        = "{0} DB"
        LblExportFolder   = "Cartella:"
        LblDefaultFolder  = "Desktop (predefinito)"
        BtnExportCsv      = "Esporta Tabella CSV"
        TypeGlobal        = "Globale"
        TypeInstance      = "Istanza"
        LblPlc            = "PLC {0}"
        LblPlcName        = "PLC: {0}"
        LblPlcIp          = "IP: {0}"
        LblPlcTsap        = "TSAP: {0}"
        BtnEditPlcInfo    = "Modifica"
        DlgPlcInfoTitle   = "Informazioni PLC"
        DlgPlcName        = "Nome PLC:"
        DlgPlcIp          = "Indirizzo IP:"
        DlgPlcTsap        = "TSAP:"
        RowPlcName        = "Nome PLC"
        RowIpAddress      = "Indirizzo IP"
        RowTsap           = "TSAP"
        ColTag            = "TAG"
        ColDB             = "DB"
        ColOffset         = "Offset"
        ColType           = "Tipo"
        ColDescription    = "Descrizione"
        ColUnit           = "Unita"
        ColRepere         = "Riferimento"
        ColCoef           = "Coef"
        MsgExportCsvDone  = "Esportazione CSV completata!"
        MsgOptimizedWarning = "DB ottimizzati (senza offset):"
        MsgXmlExportError = "{0}: Errore esportazione XML"
        MsgXmlParseError  = "{0}: Errore parsing XML"
        MsgError          = "Errore"
        MsgInfo           = "Informazione"
        MsgConfirm        = "Conferma"
        MsgNoInstance     = "Selezionare un'istanza TIA Portal."
        MsgConnectFirst   = "Connettersi prima a TIA Portal."
        MsgNoSelection    = "Selezionare almeno un DataBlock."
        MsgScanError      = "Errore durante la scansione:`n{0}"
        MsgConnectError   = "Errore di connessione:`n{0}"
        MsgOpennessSecurityError = "Accesso TIA Openness negato (errore di sicurezza).`n`nL'account Windows che esegue TIA Portal non e membro del gruppo locale << Siemens TIA Openness >>.`n`nSoluzione (come amministratore): aggiungere l'utente a tale gruppo tramite lusrmgr.msc, o da riga di comando:`n  net localgroup `"Siemens TIA Openness`" `"{0}`" /add`n`nQuindi disconnettersi da Windows (o riavviare) e riavviare TIA Portal.`n`nDettaglio:`n{1}"
        BtnCopyCommand    = "Copia il comando"
        MsgCopied         = "Comando copiato negli appunti."
        MsgConnectOk      = "Connesso al progetto: {0}`n{1} PLC rilevati"
        MsgDisconnectOk   = "Disconnesso."
        MsgLoadError      = "Errore durante il caricamento:`n{0}"
        MsgExportSuccess  = "Riusciti: {0}"
        MsgExportErrors   = "Errori: {0}"
        MsgExportFolder   = "Cartella: {0}"
        MsgExportDetail   = "Dettagli errori:"
        MsgConfirmClose   = "Un'esportazione e in corso. Vuoi davvero chiudere?"
        MsgNoProject      = "Nessun progetto aperto in TIA Portal."
        MsgNoPlc          = "Nessun PLC trovato nel progetto."
        MsgProcessNotFound = "Processo TIA Portal non trovato."
        MsgBlockNotFound  = "{0}: Blocco non trovato"
        MsgDllRequired    = "Selezionare prima una versione di TIA Portal."
        MsgRestartRequired = "DLL gia caricata. Cambiare versione richiede il riavvio dell'applicazione."
        TipScan           = "Cercare istanze TIA Portal in esecuzione"
        TipConnect        = "Connettersi all'istanza selezionata"
        TipDisconnect     = "Disconnettersi da TIA Portal"
        TipLoadDBs        = "Caricare la lista dei DataBlocks del progetto"
        TipExportCsv      = "Esportare i DataBlocks selezionati come tabella CSV (1 file per PLC)"
        TipBrowse         = "Scegliere la cartella di esportazione"
        # --- Export Format ---
        LblExportFormat   = "Formato di esportazione:"
        OptCsvSiemens     = "Tabella di scambio CSV"
        OptVarLstEwon     = "var_lst (Ewon)"
        OptPcVue          = "PcVue Architect (.csv)"
        LblEwonRepere     = "Prefisso tag (opz.):"
        LblEwonTopic      = "Topic:"
        LblEwonPage       = "Pagina:"
        BtnExportEwon     = "Esporta var_lst"
        TipExportEwon     = "Esportare i DataBlocks selezionati come var_lst.csv (Ewon Flexy)"
        MsgExportEwonDone = "Esportazione var_lst completata!"
        BtnExportPcVue    = "Esporta PcVue"
        TipExportPcVue    = "Esportare in formato PcVue Architect (1 file CSV per DB)"
        MsgExportPcVueDone = "Esportazione PcVue completata!"
        MsgInconsistentBlock = "Blocco inconsistente --compilare il progetto TIA Portal prima dell'esportazione"
        MsgOnlineModeError = "Esportazione non possibile in modalita online (connessi al PLC). Mettere TIA Portal offline (disconnettere dal PLC) e riprovare l'esportazione."
        MsgOnlinePlcList  = "PLC interessati: {0}"
        LangLabel         = "Lingua:"
    }
}

function T([string]$Key) {
    $s = $Script:Strings[$Script:CurrentLanguage]
    if ($s -and $s.ContainsKey($Key)) { return $s[$Key] }
    # Fallback to French
    $fr = $Script:Strings["FR"]
    if ($fr -and $fr.ContainsKey($Key)) { return $fr[$Key] }
    return "[$Key]"
}

function Set-Language([string]$Lang) {
    if ($Script:Strings.ContainsKey($Lang)) {
        $Script:CurrentLanguage = $Lang
        Set-AppStateValue -Key "Language" -Value $Lang
    }
}

function Get-Language { return $Script:CurrentLanguage }
